---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	ground(ground)
	plan(plan)
	agent(agent)
	tools(tools)
	update_plan(update_plan)
	synthesize(synthesize)
	__end__([<p>__end__</p>]):::last
	__start__ --> ground;
	agent -.-> synthesize;
	agent -.-> tools;
	ground --> plan;
	plan --> agent;
	tools --> update_plan;
	update_plan --> agent;
	synthesize --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
