"""
The per-model confidence overlay the USER writes (2026-08-16).

`core/confidence_calibration.py` is the SHIPPED baseline — a generated data module the wheel
carries, regenerated by utilities/confidence_calibrate.py. It is read-only at runtime: a command
writing into it would be clobbered by /update and is not even writable in a pipx install.

So `/confidence tune` and `/confidence set` write HERE instead — one JSON file in user data
(`database/confidence_calibration.json`), keyed by model tag, that wins over the shipped table.
Same precedent as database/permissions.json: durable, user-owned, gitignored, survives /update.

One owner, one parser: core/confidence reads through entry_for(), commands/confidence writes
through write_entry()/clear_entry(). Fail-soft throughout — a garbled or unreadable overlay is
recorded in load_problem() and treated as empty, because a confidence failure must never cost
the answer.

LEAF: stdlib + config only.
"""

from __future__ import annotations

import json
import os
from datetime import date
from pathlib import Path

from config import get_config

_FILENAME = "confidence_calibration.json"

# Cached parse, invalidated by mtime — the threshold lookup runs per streamed answer.
_cache: dict = {"key": None, "data": {}}
_problem: str = ""


def store_path() -> Path:
    """Where the overlay lives: <database>/confidence_calibration.json."""
    return Path(get_config().path("database")) / _FILENAME


def _reset_cache() -> None:
    """Drop the cached parse (a write, or a test)."""
    global _problem
    _cache["key"] = None
    _cache["data"] = {}
    _problem = ""


def load_problem() -> str:
    """Why the overlay could not be read (empty when fine). Surfaced by /confidence."""
    return _problem


def read() -> dict:
    """The whole overlay as {lowercased tag: record}. Empty on any problem — never raises."""
    global _problem
    path = store_path()
    try:
        stat = path.stat()
        key = (str(path), stat.st_mtime_ns, stat.st_size)
    except OSError:
        _reset_cache()
        return {}
    if _cache["key"] == key:
        return _cache["data"]

    data: dict = {}
    _problem = ""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            for tag, rec in raw.items():
                if isinstance(rec, dict):
                    data[str(tag).lower()] = dict(rec)
        else:
            _problem = f"{path.name} is not a JSON object — ignoring it"
    except (OSError, ValueError) as exc:
        _problem = f"{path.name} could not be read ({exc}) — using the shipped thresholds"
        data = {}

    _cache["key"] = key
    _cache["data"] = data
    return data


def entry_for(model) -> "dict | None":
    """The user's record for `model` (tag case-insensitive), or None."""
    return read().get(str(model or "").lower()) or None


def write_entry(model, enter: float, exit: float, *, source: str,
                tokens: int = 0, prompts: int = 0) -> None:
    """Record the user's thresholds for one model. `source` is 'tuned' (measured by
    /confidence tune) or 'manual' (typed via /confidence set) — the status readout says which.
    Written atomically so a crash mid-write can't leave a truncated overlay behind."""
    data = dict(read())
    data[str(model or "").lower()] = {
        "enter": float(enter),
        "exit": float(exit),
        "tokens": int(tokens),
        "prompts": int(prompts),
        "at": date.today().isoformat(),
        "source": str(source),
    }
    _write_all(data)


def clear_entry(model) -> bool:
    """Drop one model's record. Returns whether there was one."""
    data = dict(read())
    if data.pop(str(model or "").lower(), None) is None:
        return False
    _write_all(data)
    return True


def _write_all(data: dict) -> None:
    path = store_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, path)
    _reset_cache()
