"""
Per-model confidence thresholds — GENERATED by `utilities/confidence_calibrate.py`; do not edit
by hand (re-run the utility instead).

For each model tag: `enter` = the sampled-token probability under which a CLEAN answer's content
tokens fall only 5 % of the time (the run-opening threshold), `exit` = the 10 % point (the
hysteresis exit), measured under main's own scoring unit — per-token p over `core/confidence`'s
low_runs filter (neutral punctuation and closed-class stopwords excluded) — on the synthesizer's
real prompt shape. So "marked" means "worse than 95 % of this model's clean output", per model,
instead of one fixed number that the confidence_coloring isolate's data showed to be off by up to
an order of magnitude across model sizes.

`core/confidence.threshold()` consults this table when `runtime.confidence_threshold` is `auto`.
"""

# tag (lowercase) -> {"enter": p, "exit": p, "tokens": n, "prompts": n, "at": "YYYY-MM-DD"}
CALIBRATION: dict = {'gemma4:e4b': {'at': '2026-08-16',
                'enter': 0.436,
                'exit': 0.7114,
                'prompts': 55,
                'tokens': 459},
 'qwen3-coder:30b': {'at': '2026-08-16',
                     'enter': 0.6077,
                     'exit': 0.8705,
                     'prompts': 55,
                     'tokens': 930},
 'qwen3.6:27b': {'at': '2026-08-16',
                 'enter': 0.2229,
                 'exit': 0.4247,
                 'prompts': 55,
                 'tokens': 1279},
 'qwen3.8:27b': {'at': '2026-08-16',
                 'enter': 0.2229,
                 'exit': 0.4247,
                 'inherited_from': 'qwen3.6:27b',
                 'prompts': 0,
                 'tokens': 0}}
