"""
Per-model confidence thresholds — GENERATED by `utilities/confidence_calibrate.py`; do not edit
by hand (re-run the utility instead), with the ONE exception noted below.

For each model tag: `enter` = the sampled-token probability under which a CLEAN answer's content
tokens fall only 5 % of the time (the run-opening threshold), `exit` = the 10 % point (the
hysteresis exit), measured under main's own scoring unit — per-token p over `core/confidence`'s
low_runs filter (neutral punctuation and closed-class stopwords excluded) — on the synthesizer's
real prompt shape. So "marked" means "worse than 95 % of this model's clean output", per model,
instead of one fixed number that the confidence_coloring isolate's data showed to be off by up to
an order of magnitude across model sizes.

MEASURED vs ESTIMATED. A row is normally a MEASUREMENT: `tokens`/`prompts` record the sample it
came from and `at` when it was taken. A row may instead be an ESTIMATE, marked by
`source: 'estimated'` plus an `estimated_from` string naming exactly what it was derived from —
used only when the daemon cannot measure a shipped model at all (today: Ollama 0.32.13 returns
per-token logprobs for qwen3.8 on the first chunk only, so `qwen3.8:27b` scores ~11 tokens and
`core.calibration.MIN_TOKENS` correctly refuses to record). An estimate is a best guess, never a
per-model claim, and every readout that shows it must say so: `/confidence` names it as estimated
and points at `/confidence tune`, which replaces it with a real measurement (into the user overlay,
core/confidence_store) the moment the daemon supports the model. Never present an estimated row as
a measurement — that claim is the entire point of calibrating per model.

`core/confidence.threshold()` consults this table when `runtime.confidence_threshold` is `auto`.
"""

# tag (lowercase) -> {"enter": p, "exit": p, "tokens": n, "prompts": n, "at": "YYYY-MM-DD"}
# An estimated row additionally carries {"source": "estimated", "estimated_from": "<why>"}.
CALIBRATION: dict = {'qwen3.5:0.8b': {'at': '2026-08-16',
                  'enter': 0.0261,
                  'exit': 0.0543,
                  'prompts': 55,
                  'tokens': 1840},
 'qwen3.5:2b': {'at': '2026-08-16',
                'enter': 0.0546,
                'exit': 0.0998,
                'prompts': 55,
                'tokens': 1872},
 'qwen3.5:4b': {'at': '2026-08-16',
                'enter': 0.1766,
                'exit': 0.314,
                'prompts': 55,
                'tokens': 796},
 'qwen3.5:9b': {'at': '2026-08-16',
                'enter': 0.2538,
                'exit': 0.4897,
                'prompts': 55,
                'tokens': 737},
 'qwen3.6:27b': {'at': '2026-08-16',
                 'enter': 0.2229,
                 'exit': 0.4247,
                 'prompts': 55,
                 'tokens': 1279},
 'qwen3.6:35b': {'at': '2026-08-16',
                 'enter': 0.3859,
                 'exit': 0.6369,
                 'prompts': 55,
                 'tokens': 1142},
 'qwen3.8:27b': {'at': '2026-08-16',
                 'enter': 0.2229,
                 'exit': 0.4247,
                 'estimated_from': "qwen3.6:27b, measured 2026-08-16 over 1279 tokens — a "
                                   "27.8B sibling of this 27.3B model. Ollama 0.32.13 returns "
                                   "per-token logprobs for qwen3.8 on the first chunk only, so "
                                   "this model cannot be measured directly yet; /confidence tune "
                                   "replaces this with a real measurement once it can.",
                 'prompts': 0,
                 'source': 'estimated',
                 'tokens': 0}}
